### ISSUE TITLE
Add support of multiple path

### ISSUE THREAD

**Issue by yinonov** [megahertz/spech#3]
### common use case missing for handling convention folder structure of MDs in repos
md files in repos are usually `readme.md` and more elaborated docs at `/docs`.
Therefore I'd rather automate the process and report by providing a multi path
e.g. `spech readme.md, docs/*.md`

the command does iterate over the MDs in nested folders but it also run on unrelated `CHANGELOG.md` in the process

**Comment by megahertz** [comment]
Does `spech readme.md 'docs/*.md'` works for your case?

**Comment by yinonov** [comment]
yes it does! maybe state it in the cli --help general options?

Thanks

**Comment by megahertz** [comment]
Will add it later
