### ISSUE TITLE
ci-job-number - should be a devdependency?

### ISSUE THREAD

**Issue by gullerya** [megahertz/spech#4]
Right now this lib pulls in quite a lot of dependencies which are mostly related to this `ci-job-number` dependency of it's own.
From the name I'm wandering - should this one be in `devDependencies` and not in the `dependencies`?

**Comment by megahertz** [comment]
No, it's not a dev dependency, since spech can be configured to run only on the first instance of CI pipeline. It's pretty small: 3.4kb, 5 files without nested dependencies, so I don't think it should be removed or replaced.
